.extern _ZN5Riscv3ivtEv
.global _ZN5Riscv3ivtEv
.type _ZN5Riscv3ivtEv, @function
.align 4


_ZN5Riscv3ivtEv:
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv // tajmer?
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv //TODO konzola
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv
jal x0, _ZN5Riscv14supervisorTrapEv

//jal x0, _ZN5Riscv14supervisorTrapEv

